# KubeLinter GitHub Actions workflow
# https://github.com/marketplace/actions/kube-linter

name: Lint Kubernetes configuration files

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint-kubernetes:
    name: Lint Kubernetes configuration files
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Lint Kubernetes YAML files
        uses: stackrox/kube-linter-action@v1.0.6
        id: kube-linter-action-scan
        with:
          directory: config
